version: '3.1'
services:
  wordpress:
    image: wordpress
    links:
      - mariadb:mysql
    environment:
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_USER=root
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./database:/var/lib/mysql